export const CrossChainReceiverABI = [
  { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
  { inputs: [], name: 'AgentNotFound', type: 'error' },
  { inputs: [], name: 'InvalidAddress', type: 'error' },
  { inputs: [], name: 'InvalidChainId', type: 'error' },
  { inputs: [], name: 'NotAuthorizedRelayer', type: 'error' },
  { inputs: [{ internalType: 'address', name: 'owner', type: 'address' }], name: 'OwnableInvalidOwner', type: 'error' },
  { inputs: [{ internalType: 'address', name: 'account', type: 'address' }], name: 'OwnableUnauthorizedAccount', type: 'error' },
  { inputs: [], name: 'ReentrancyGuardReentrantCall', type: 'error' },
  { inputs: [], name: 'SourceChainAlreadyExists', type: 'error' },
  { inputs: [], name: 'SourceChainNotRegistered', type: 'error' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'sourceChainId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'agentOwner', type: 'address' },
      { indexed: false, internalType: 'uint256', name: 'timestamp', type: 'uint256' },
    ],
    name: 'AgentRemoved',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'sourceChainId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'agentOwner', type: 'address' },
      { indexed: false, internalType: 'string', name: 'name', type: 'string' },
      { indexed: false, internalType: 'uint256', name: 'reputationScore', type: 'uint256' },
      { indexed: false, internalType: 'uint256', name: 'timestamp', type: 'uint256' },
    ],
    name: 'AgentSynced',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
      { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'address', name: 'relayer', type: 'address' },
      { indexed: false, internalType: 'bool', name: 'authorized', type: 'bool' },
    ],
    name: 'RelayerUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'chainId', type: 'uint256' },
      { indexed: false, internalType: 'string', name: 'name', type: 'string' },
      { indexed: false, internalType: 'address', name: 'hubContract', type: 'address' },
    ],
    name: 'SourceChainAdded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: 'uint256', name: 'chainId', type: 'uint256' }],
    name: 'SourceChainRemoved',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [{ indexed: false, internalType: 'uint256', name: 'newThreshold', type: 'uint256' }],
    name: 'StaleThresholdUpdated',
    type: 'event',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'chainId', type: 'uint256' },
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'address', name: 'hubContract', type: 'address' },
    ],
    name: 'addSourceChain',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'authorizedRelayers',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'sourceChainId', type: 'uint256' },
      { internalType: 'address[]', name: 'agentOwners', type: 'address[]' },
      { internalType: 'string[]', name: 'names', type: 'string[]' },
      { internalType: 'string[]', name: 'metadataURIs', type: 'string[]' },
      { internalType: 'string[][]', name: 'capabilities', type: 'string[][]' },
      { internalType: 'uint256[]', name: 'reputationScores', type: 'uint256[]' },
      { internalType: 'uint256[]', name: 'totalTasksCompleted', type: 'uint256[]' },
    ],
    name: 'batchSyncAgents',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'sourceChainId', type: 'uint256' },
      { internalType: 'address', name: 'agentOwner', type: 'address' },
    ],
    name: 'getAgent',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'sourceChainId', type: 'uint256' },
          { internalType: 'address', name: 'owner', type: 'address' },
          { internalType: 'string', name: 'name', type: 'string' },
          { internalType: 'string', name: 'metadataURI', type: 'string' },
          { internalType: 'string[]', name: 'capabilities', type: 'string[]' },
          { internalType: 'uint256', name: 'reputationScore', type: 'uint256' },
          { internalType: 'uint256', name: 'totalTasksCompleted', type: 'uint256' },
          { internalType: 'uint256', name: 'lastSyncTimestamp', type: 'uint256' },
          { internalType: 'bool', name: 'isActive', type: 'bool' },
        ],
        internalType: 'struct CrossChainReceiver.RemoteAgent',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'sourceChainId', type: 'uint256' },
      { internalType: 'address', name: 'agentOwner', type: 'address' },
    ],
    name: 'getAgentCapabilities',
    outputs: [{ internalType: 'string[]', name: '', type: 'string[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'sourceChainId', type: 'uint256' }],
    name: 'getAgentCountByChain',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: 'capability', type: 'string' },
      { internalType: 'uint256', name: 'sourceChainId', type: 'uint256' },
    ],
    name: 'getAgentsByCapability',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'sourceChainId', type: 'uint256' },
          { internalType: 'address', name: 'owner', type: 'address' },
          { internalType: 'string', name: 'name', type: 'string' },
          { internalType: 'string', name: 'metadataURI', type: 'string' },
          { internalType: 'string[]', name: 'capabilities', type: 'string[]' },
          { internalType: 'uint256', name: 'reputationScore', type: 'uint256' },
          { internalType: 'uint256', name: 'totalTasksCompleted', type: 'uint256' },
          { internalType: 'uint256', name: 'lastSyncTimestamp', type: 'uint256' },
          { internalType: 'bool', name: 'isActive', type: 'bool' },
        ],
        internalType: 'struct CrossChainReceiver.RemoteAgent[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'sourceChainId', type: 'uint256' }],
    name: 'getAgentsBySourceChain',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'sourceChainId', type: 'uint256' },
          { internalType: 'address', name: 'owner', type: 'address' },
          { internalType: 'string', name: 'name', type: 'string' },
          { internalType: 'string', name: 'metadataURI', type: 'string' },
          { internalType: 'string[]', name: 'capabilities', type: 'string[]' },
          { internalType: 'uint256', name: 'reputationScore', type: 'uint256' },
          { internalType: 'uint256', name: 'totalTasksCompleted', type: 'uint256' },
          { internalType: 'uint256', name: 'lastSyncTimestamp', type: 'uint256' },
          { internalType: 'bool', name: 'isActive', type: 'bool' },
        ],
        internalType: 'struct CrossChainReceiver.RemoteAgent[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getAllRemoteAgents',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'sourceChainId', type: 'uint256' },
          { internalType: 'address', name: 'owner', type: 'address' },
          { internalType: 'string', name: 'name', type: 'string' },
          { internalType: 'string', name: 'metadataURI', type: 'string' },
          { internalType: 'string[]', name: 'capabilities', type: 'string[]' },
          { internalType: 'uint256', name: 'reputationScore', type: 'uint256' },
          { internalType: 'uint256', name: 'totalTasksCompleted', type: 'uint256' },
          { internalType: 'uint256', name: 'lastSyncTimestamp', type: 'uint256' },
          { internalType: 'bool', name: 'isActive', type: 'bool' },
        ],
        internalType: 'struct CrossChainReceiver.RemoteAgent[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getSourceChains',
    outputs: [
      {
        components: [
          { internalType: 'uint256', name: 'chainId', type: 'uint256' },
          { internalType: 'string', name: 'name', type: 'string' },
          { internalType: 'address', name: 'hubContract', type: 'address' },
          { internalType: 'bool', name: 'isActive', type: 'bool' },
        ],
        internalType: 'struct CrossChainReceiver.SourceChain[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'sourceChainId', type: 'uint256' },
      { internalType: 'address', name: 'agentOwner', type: 'address' },
    ],
    name: 'isAgentActive',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'sourceChainId', type: 'uint256' },
      { internalType: 'address', name: 'agentOwner', type: 'address' },
    ],
    name: 'isAgentStale',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'sourceChainId', type: 'uint256' },
      { internalType: 'address', name: 'agentOwner', type: 'address' },
    ],
    name: 'removeAgent',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'chainId', type: 'uint256' }],
    name: 'removeSourceChain',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: 'relayer', type: 'address' },
      { internalType: 'bool', name: 'authorized', type: 'bool' },
    ],
    name: 'setRelayer',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'threshold', type: 'uint256' }],
    name: 'setStaleThreshold',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'sourceChains',
    outputs: [
      { internalType: 'uint256', name: 'chainId', type: 'uint256' },
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'address', name: 'hubContract', type: 'address' },
      { internalType: 'bool', name: 'isActive', type: 'bool' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'staleThreshold',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'sourceChainId', type: 'uint256' },
      { internalType: 'address', name: 'agentOwner', type: 'address' },
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'string', name: 'metadataURI', type: 'string' },
      { internalType: 'string[]', name: 'capabilities', type: 'string[]' },
      { internalType: 'uint256', name: 'reputationScore', type: 'uint256' },
      { internalType: 'uint256', name: 'totalTasksCompleted', type: 'uint256' },
    ],
    name: 'syncAgent',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalRemoteAgents',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'chainId', type: 'uint256' },
      { internalType: 'address', name: 'hubContract', type: 'address' },
    ],
    name: 'updateSourceChainHub',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const;
